version: '3.8'
services:
  playwright-test:
    image: pw-api-test
    build: 
      context: .
      dockerfile: ./Dockerfile
    command: npm run conduit-bvt
    volumes:
      - ./playwright-report/:/app/playwright-report
      - ./test-results/:/app/test-results